version: '3.6'

services:
  kong-database:
    image: postgres:9.6-alpine@sha256:c4c2becb0470566d3ff0c22f84e3ed9c4b0dbd96a0d873499e708952d8040738
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migration:
    image: kong:0.15.0-alpine@sha256:3b8aceaa99a0e6c9a3721e7cc82731e4b64ff0c42147b8a11e605ae22e4c53c2
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
    command: kong migrations up

  kong:
    image: kong:0.14.1-alpine@sha256:a3ed07b0934defcabc77e1cd65701803f94610e5cb460060814249fbba28362c
    depends_on:
      - kong-database
      - kong-migration
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    expose:
      - 8000
      - 8001
      - 8443
      - 8444
    ports:
      - "8000:8000"
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://127.0.0.1:8000 || exit 1"]
      interval: 5s
      retries: 10

  kongfig:
    build: .
    depends_on:
      - kong-database
      - kong-migration
      - kong
    volumes:
      - ./examples:/etc/kongfig/:ro
    command: ["apply", "-f", "/etc/kongfig/config.example.yaml"]
    environment:
      - POD_NAMESPACE=dev
      - DOMAIN_NAME=pager.com
      - SVC_DOMAIN=dev.svc.cluster.local
